"""empty message

Revision ID: a6b52eaa92a3
Revises: 
Create Date: 2022-07-20 18:45:31.662311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b52eaa92a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Pages', 'author',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_foreign_key(None, 'Pages', 'user', ['author'], ['username'])
    op.create_foreign_key(None, 'Pages', 'Spaces', ['space'], ['id'])
    op.create_unique_constraint(None, 'Spaces', ['homepage'])
    op.create_foreign_key(None, 'Spaces', 'Spaces', ['parent'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Spaces', type_='foreignkey')
    op.drop_constraint(None, 'Spaces', type_='unique')
    op.drop_constraint(None, 'Pages', type_='foreignkey')
    op.drop_constraint(None, 'Pages', type_='foreignkey')
    op.alter_column('Pages', 'author',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
